# Plugin
pluginGroup = com.wooongyee.jvmbaekjoon
pluginName = JvmBaekjoon
pluginRepositoryUrl = https://github.com/wooongyee/JvmBaekjoon
pluginVersion = 0.1.0

# IntelliJ Platform
platformVersion = 2025.3
pluginSinceBuild = 233

# Bundled Plugins
platformBundledPlugins = com.intellij.java,org.jetbrains.kotlin

platformPlugins =

# Bundled Modules
platformBundledModules =

# Gradle
gradleVersion = 9.2.1

# Kotlin
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true

org.gradle.jvmargs = -Xmx2048m -XX:MaxMetaspaceSize=1024m
